### ISSUE TITLE
EKCO Operator logs do not show the node name correctly.

### ISSUE THREAD

**Issue by cremerfc** [replicatedhq/ekco#14]
https://github.com/replicatedhq/ekco/blob/a34ddcfa7d6d7ca3153fe181acd6b1c5da34631c/pkg/cluster/clear_node.go#L33

I was testing HA scenarios on an embedded cluster on GCP. We were looking at the Operator logs and noticed that the messages like:

2020-07-15T23:24:30.135Z	INFO	cluster/clear_node.go:33	Force deleting pod default/app-direct-deployment-6554d759f8-nr5xv on node %!s(MISSING)

Here is a screenshot as well:

<img width="2000" alt="Screen Shot 2020-07-14 at 3 56 52 PM" src="https://user-images.githubusercontent.com/13663801/87717103-dfee5780-c77d-11ea-85e9-3ef457536f4c.png">

It was very hard to troubleshoot without knowing the node name

**Comment by emosbaugh** [comment]
This has been fixed https://github.com/replicatedhq/ekco/commit/a34ddcfa7d6d7ca3153fe181acd6b1c5da34631c
