### ISSUE TITLE
EKCO tries to scale Monitors back to 1, causing rook-ceph-operator to get stuck

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/ekco#26]
I'm running a 3-master kURL cluster with Rook 1.4. I ran into an issue where ekco's behavior seemed to cause the rook-ceph-operator to get stuck.

At some point ekco believed there were less than 3 nodes in my cluster, and tried to scale Rook monitors back to 1. The Rook operator didn’t like that; it appeared to get into a loop where it would fail to scale to less than 2 because it would lose quorum, and even when the CephCluster definition was set back to 3 monitors it didn’t break out of that loop until I restarted rook-ceph-operator.

I don’t have a clear picture how it happened, but I believe ekco thought there was only 1 node because etcd had a brief outage.

The gist is: if CephCluster is configured to use 3 monitors, ekco shouldn't switch it back to 1 because that fails and seems to cause issues in the rook-ceph-operator.

**Comment by MikaelSmith** [comment]
I think this happens whenever I modify the CephCluster config.

**Comment by tamarahenson** [comment]
Update:  internal request #29160 EKCO should not scale mons down to 1 after scaling to 3 has been resolved.

**Comment by MikaelSmith** [comment]
This may have been addressed in ekco 0.10.0. A changelog or release notes would be appreciated.
